dependencies:
- name: cloud-native-poc-pdf
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jm15
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jm16
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- name: jm21
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: tag
  repository: http://jenkins-x-chartmuseum:8080
  version: found
